import { uniqueId } from "lodash";

import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconGitMerge,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconShoppingCart,
  IconAperture,
  IconLayout,
  IconSettings,
  IconHelp,
  IconZoomCode,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBorderStyle2,
  IconLockAccess,
  IconAppWindow,
  IconNotebook,
  IconFileCheck,
  IconChartHistogram,
  IconListTree,
  IconChartArcs3,
  IconChartPpf,
  IconChartScatter,
  IconChartPie2,
  IconPageBreak,
  IconBriefcase,
  IconShield,
} from "@tabler/icons-react";
import { ElementType } from "react-spring";
import { NavGroup } from "@/app/DashboardLayout/types/layout/sidebar";

const Menuitems: NavGroup[] = [
  {
    navlabel: true,
    subheader: "Home",
  },

  {
    id: uniqueId(),
    title: "Modern",
    icon: IconAperture,
    href: "/",
    chip: "New",
    chipColor: "secondary",
  },
  {
    id: uniqueId(),
    title: "eCommerce",
    icon: IconShoppingCart,
    href: "/dashboards/ecommerce",
  },
  {
    id: uniqueId(),
    title: "Frontend pages",
    icon: IconAppWindow,
    href: "/",
    children: [
      {
        id: uniqueId(),
        title: "Homepage",
        icon: IconPoint,
        href: "/homepage",
      },
      {
        id: uniqueId(),
        title: "About Us",
        icon: IconPoint,
        href: "/about",
      },
      {
        id: uniqueId(),
        title: "Blog",
        icon: IconPoint,
        href: "/blog",
      },
      {
        id: uniqueId(),
        title: "Blog Details",
        icon: IconPoint,
        href: "/blog/Blog_1",
      },
      {
        id: uniqueId(),
        title: "Contact",
        icon: IconPoint,
        href: "/contact",
      },
      {
        id: uniqueId(),
        title: "Portfolio",
        icon: IconPoint,
        href: "/portfolio",
      },
      {
        id: uniqueId(),
        title: "Pricing",
        icon: IconPoint,
        href: "/pricing",
      },
    ],
  },
  {
    navlabel: true,
    subheader: "Apps",
  },

  {
    id: uniqueId(),
    title: "Blog",
    icon: IconChartDonut3,
    href: "/DashboardLayout/apps/blog-management",
    children: [
      {
        id: uniqueId(),
        title: "Manage Posts",
        icon: IconPoint,
        href: "/DashboardLayout/apps/blog-management",
      },
      {
        id: uniqueId(),
        title: "Comments",
        icon: IconPoint,
        href: "/DashboardLayout/apps/blog/comments",
      },
    ],
  },

  {
    id: uniqueId(),
    title: "Users",
    icon: IconUserCircle,
    href: "/DashboardLayout/apps/user-profile/profile",
    children: [
      {
        id: uniqueId(),
        title: "Profile",
        icon: IconPoint,
        href: "/DashboardLayout/apps/user-profile/profile",
      },
      {
        id: uniqueId(),
        title: "User Roles",
        icon: IconPoint,
        href: "/DashboardLayout/apps/user-profile/roles",
      },
    ],
  },

  {
    navlabel: true,
    subheader: "Pages",
  },
  {
    id: uniqueId(),
    title: "Account Setting",
    icon: IconUserCircle,
    href: "/theme-pages/account-settings",
  },
  {
    id: uniqueId(),
    title: "FAQ",
    icon: IconHelp,
    href: "/theme-pages/faq",
  },
  {
    id: uniqueId(),
    title: "Tabler Icon",
    icon: IconMoodSmile,
    href: "/icons",
  },
];

export default Menuitems;